### ISSUE TITLE
Crash when trying to create a skin preset

### ISSUE THREAD

**Issue by GameduJS** [mineblock11/SkinShuffle#17]
### Describe the issue

Minecraft version: 1.20
Mod version: latest on Modrinth

I opened a world and instantly opened the Skinpresets screen.
When I tried to create a new preset, my games crashed.

### Relevant log output

https://mclo.gs/2wCwILw

### Extra information

I disabled all other mods, it still crashes

**Comment by mineblock11** [comment]
![image](https://github.com/mineblock11/SkinShuffle/assets/93472213/070bbe8e-3bd1-470d-ae6a-6f53e30bd488)

We do not support feather client or any clients that steal existing projects. Please either uninstall feather client or do not use our mod.

**Comment by mineblock11** [comment]
https://hypixel.net/threads/feather-client-what-you-should-know-about-this-client.4801748/
