### ISSUE TITLE
minecraft comes alive mod 1.20.1 crash

### ISSUE THREAD

**Issue by lostopkk** [mineblock11/SkinShuffle#28]
https://mclo.gs/g2rYgWg

**Comment by mineblock11** [comment]
> at org.quiltmc.qsl.networking.api.client.ClientPlayNetworking.send(ClientPlayNetworking.java:228)

**Comment by mineblock11** [comment]
This is a quilt bug

**Comment by lostopkk** [comment]
> This is a quilt bug

it may even be, but this crash only occurred when I activated the mca. before it worked 100% fine with the quilt

**Comment by mineblock11** [comment]
It's related to mca then. not skinshuffle
