### ISSUE TITLE
On the pause screen, click Esc again to not return to Game

### ISSUE THREAD

**Issue by WzczChenX** [mineblock11/SkinShuffle#29]
### Describe the issue

Currently happening:
There is no response when clicking Esc

I want it to happen:
On the pause interface, it disappears like vanilla when you click Esc
Player Back to game.

（I don't know if this counts as a vulnerability, and if it's intentional, hopefully a configuration button can be added to modify it 
Thank!）

### SkinShuffle version

0.3.0+1.20

**Comment by enjarai** [comment]
I can see where this issue stems from, it'll be fixed in the next update.
