### ISSUE TITLE
Character looking on cursor with offset on y axis

### ISSUE THREAD

**Issue by JumperOnJava** [mineblock11/SkinShuffle#3]
Cursor is at red dot
I'm using GUI scale 2 on 1920*1080 monitor
![image](https://github.com/mineblock11/SkinShuffle/assets/59884606/2681d7ce-6f3c-4e0e-af73-d8ec27b31d54)

**Comment by mineblock11** [comment]
This will be fixed for the next beta release.

If you wish to disable the cursor following, you can change it to the rotation rendering style in the configuration screen.
