### ISSUE TITLE
Can't close game menu with esc

### ISSUE THREAD

**Issue by JustLetterV** [mineblock11/SkinShuffle#37]
### Describe the issue

In vanilla game menu can be closed with esc, but when I have SkinShuffle installed I can't do that anymore. I only have SkinShuffle 0.3.0+1.20 and Fabric API 0.85.0+1.20.1 installed. With game menu I mean this:
![](https://github.com/mineblock11/SkinShuffle/assets/75657829/ea4a737b-378d-4d24-be1d-d85689257b02)

### SkinShuffle version

0.3.0+1.20

**Comment by Benonardo** [comment]
Duplicate of #35
