### ISSUE TITLE
SkinShuffle completely breaks Esc button

### ISSUE THREAD

**Issue by Felix14-v2** [mineblock11/SkinShuffle#38]
### Description
You just can't use `Esc` to close the vanilla/modded menus.

### SkinShuffle version
0.3.0-1.20

### Logs

[latest.log](https://github.com/mineblock11/SkinShuffle/files/12114645/latest.log)

### Extra information

Tested with only SkinShuffle and Fabric API.

**Comment by Benonardo** [comment]
Duplicate of a bunch of issues, fixed by #30

**Comment by Felix14-v2** [comment]
Oh, sorry for inattention, then i'm closing this one
