### ISSUE TITLE
Missing arrows on preset screen

### ISSUE THREAD

**Issue by Pixiequinn** [mineblock11/SkinShuffle#8]
### Describe the issue

The arrows are missing so you cant scroll between your saved presets, nor can you access the other ones ( you can see) to use for edit copy deete or even select.  The first one works so I can re add a new skin anytime I want to switch, but the carousel function is broken.

**Comment by mineblock11** [comment]
Could you provide screenshots?

**Comment by Pixiequinn** [comment]
![skinpresets](https://github.com/mineblock11/SkinShuffle/assets/137244954/cfc04c3e-e010-46d8-98d5-d0130bbcdfef)

**Comment by Pixiequinn** [comment]
so you cant scroll over to the far right or click to access anything about the other presets

**Comment by mineblock11** [comment]
Hm, might be your resource pack?

**Comment by Pixiequinn** [comment]
I disabled all my packs and restarted, I'm able to scroll through now-still no arrows its just a random click spot but still cant swap between skins

**Comment by mineblock11** [comment]
Could you provide a list of mods you have installed?
