### ISSUE TITLE
Model type stays default even when choosing slim

### ISSUE THREAD

**Issue by hhyrites** [mineblock11/SkinShuffle#9]
### Describe the issue

![Screenshot (25)](https://github.com/mineblock11/SkinShuffle/assets/70122416/2bbbca90-68b8-4ba3-ad61-6b6fa3946b3a)
![Screenshot (36)](https://github.com/mineblock11/SkinShuffle/assets/70122416/549aa637-a05f-47c8-82f5-14971bb1794a)

### Extra information

Using cracked minecraft launcher UltimMC

**Comment by mineblock11** [comment]
We do not support clients, cheats, or modifications that allow you to access the game without paying for it.
